name: "Deploy Environment"

on:
  push:
    branches:
      - dev
      - main

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
    DeployInfra:
        name: Execute terraform code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"

            - name: configure terraform values
              run: |
                cd helper_scripts
                pip install boto3
                python3 conf_tf_values.py

            - name: setup terraform
              uses: hashicorp/setup-terraform@v2


            - name: terraform apply
              run: |
                cd iac
                terraform init
                terraform apply -auto-approve

